feat: adaptive,resasing
Tei4th1/help-animals-react pull request #6
Opened 2024-11-26 09:50 UTC by Tei4th1

2024-11-27 03:39 UTC, mimimightyowl requested changes

2024-11-27 03:39 UTC, mimimightyowl commented on src/App.tsx
> -        <div
замени инлайн стили на стили styled components, можешь внутри этого же файла создать пару стилизованный контейнеров div

2024-11-27 03:39 UTC, mimimightyowl commented on src/App.tsx
> -          style={{
тоже самое

2024-11-27 03:40 UTC, mimimightyowl commented
@Tei4th1 деплой netlify сфейлился - надо исправить и добавь ссылку не в пр, а в секцию about или readme на главной странице

2024-11-28 15:51 UTC, Tei4th1 commented
> @Tei4th1 деплой netlify сфейлился - надо исправить и добавь ссылку не в пр, а в секцию about или readme на главной странице

У меня даже ссылки нет, это бот ссылку добавил

2024-12-01 04:46 UTC, mimimightyowl approved these changes

2024-12-01 04:46 UTC, merged